### PR TITLE
promote social network growth

### PR DESCRIPTION
**Pull request by ovcOS**

### CODE REVIEW

**Comment by morloy** [comment]
Looks nice! 🚀 
However, the `/social-media-contest` page looks a bit weird. How about using a modal instead of a page?

**Comment by ovcOS** [comment]
> Looks nice! 🚀
> However, the `/social-media-contest` page looks a bit weird. How about using a modal instead of a page?

For sure @morloy, this was just a quick prototype. I was planning on making it a bit nicer, maybe even have a countdown clock. Alternatively, a modal can also do the job :)

**Comment by colmarius** [comment]
@ovcOS just curious, any plan on pushing this forward? :-)

**Comment by ovcOS** [comment]
> @ovcOS just curious, any plan on pushing this forward? :-)

@colmarius yes, but it's not high priority. We will first take care of reporting and onboarding, then move on to this

**Comment by colmarius** [comment]
@ovcOS makes sense. I checked in Jira we don't have a task for it (or I couldn't find it), there should be one there added in `Up next`.

**Pull request closed without merging**
