### PR TITLE
reword features page

### PR DESCRIPTION
**Pull request by ovcOS**
General

- [x] turn feature page sections into components, they are very repetitive
- [x] remove unused image imports on each feature page
- [x] restyle top part of each feature page, make top image appear immediately
- [x] maybe do each of the feature pages' top image in the same style as the ESOP page top image (perspective view)?
- [x] update description of Title component on each feature page (Ben)
- [x] make illustrations on feature page more consistent
- [x] make capitalization of titles on feature page consistent

ESOP page

- [x] replace bulk import screenshot with proper one
- [x] replace invite stakeholder screenshot with screenshot of reminder email (we have the collaboration part in its own feature page
- [ ] Redo top screenshot in flat

Captable page
- [x] Redo pooled investment screenshot with narrower screen and ordered share classes
- [x] Minor: Redo transfer form screenshot so it includes "Add documents"
- [x] Ben: Shorten "All transaction type"

Modeling
- [x] Add missing screenshots
- [x] Diluted cap table after round, make less wide
- [x] Redo main screenshot after Jules is done with his PR

Collaboration/Due Dil
- [x] Redo top image with updated UI, also showing a dropdown of linked transactions
- [x] Data / Document section: redo screenshot featuring the document filter in action
- [x] Add screenshot of edit log (on company settings page)
- [x] add screenshot showing the blockchain notary

Investors
- [x] Redo portfolio screenshot without "all currencies converted ..." and with the blue callouts at the top
- [x] Redo portfolio history screenshot with plot and document dropdown open

Translations
- [x] German
- [ ] French

### CODE REVIEW

**Comment by bbinoy** [comment]
Cap table page

- I'd replace the top screenshot with a cap table screenshot, including the pie chart. Reason: Our transaction design is not very appealing ;)
- bulk import part at the end not like own section, but like other parts
- numbered shares: 
  - Screenshot of a transaction with the share numbers input field and the auto-assign button. 
  - make three bullets --> ledgy can auto-assign them for you for all transactions with a click, auto-assign available ones for one transaction, checks for missing or overlapping ones. 
- update screenshots for linking documents to transactions. Add bullet "properly document your legal history from the start and save hours in future due diligences" or similar
- remove "enjoy graphes..." and focus on the history part especially "filter the history by ..." and "understand the changes over time in terms of valuation, percentage or number of shares"

ESOP page

- Last major headline "Engage your employees with more transparency" as sub-part like the others
- Add bulk import section like on cap table page

Investor relations
- add reporting
- add KPIs

**Comment by bbinoy** [comment]
General

- [] restyle top part of each feature page, make top image appear immediately
- [] turn feature page sections into components, they are very repetitive
- [] maybe do each of the feature pages' top image in the same style as the ESOP page top image (perspective view)?
- [] remove unused image imports on each feature page

ESOP page

- [] replace bulk import screenshot with proper one
- [] replace invite stakeholder screenshot with screenshot of reminder email (we have the collaboration part in its own feature page

Captable page
- [] Redo transfer form screenshot so it includes "Add documents"
- [] Redo pooled investment screenshot with narrower screen and ordered share classes

Modeling
- [] Redo main screenshot after Jules is done with his PR
- [] Diluted cap table after round, make less wide

Collaboration/Due Dil
- [] Data room section: redo screenshot showing the document filter in action and less wide
- [] Think of a screenshot for the part "Granular access rights"

Investors
- [] Ben still needs to work over this page

**Comment by bbinoy** [comment]
image
Would be nice to fix this glitch of vertical alignment if text wraps to two lines.

**Comment by morloy** [comment]
image

I assume you are already aware of this…?

**Comment by ovcOS** [comment]
> image
> 
> I assume you are already aware of this…?

What do you mean by this? (Don't say the icons 💩)

**Comment by bbinoy** [comment]
Man müsste noch einmal über das Layout gehen und schauen, ob es von den Längen her passt. Hier z.B. ist der offensichtlichste Glitch, da muss man was kürzeres finden. Einfach "Relations investisseurs et portfolio" geht nicht?
image

**Pull request merged**
