### PR TITLE
[ EPIC ] LG-1115 / Rebranding

### PR DESCRIPTION
**Pull request by ovcOS**
Here it is, our new rebranded landing! 🚀

When you test, make sure that you go through:
- Links
- Modals
- Navbar menus
- Dropdowns
- RESPONSIVENESS

TODOs:
- [x] Add links in the main index page
- [x] Decide where to put Swiss icon
- [x] Add a max width to the header of the sub-pages "Data protection", "For finance", etc. Currently it's super spread out on larger screens
- [x]  Check content. Add and fix content in navbar dropdown menus (Ben).
- [ ] Check all tracking functions are where they should
- [ ] If time-permitting, style a bit more

### CODE REVIEW

**Comment by morloy** [comment]
* Nav cursor
* Nav dropdown jump
* Modal fade
* Page width
* Number of employees border radius
* More spacing

**Comment by bbinoy** [comment]
General
- [x] Checked all footer links, they work
- [ ] Favicon
- [ ] For all sections with text and graphics next to each other: The text seems to wide to me and the margin between text and image too small. 
- [ ] Many links are too small and don't have good hover effect, e.g. in user stories, on cookie policy page, ...
- [ ] On all sub-pages, the subtitle in the dark background top part spans across the full width, looking like spaghetti especially on bigger screens. I would definitely put a max-width here.

Navbar
- [ ] When using the navbar dropdown to go to a page, the dropdown won't open afterwards anymore. Hovering over another element does trigger the dropdown and then one can move sideways to get to the desired one though.
- [ ] The hover effect of the dropdown items could use some tweaking, but lower prio. E.g. x-padding of the text to the background seems a bit small to me.
- [ ] Add the remaining ressources entries and adjust subtitle texts according to mockup

Main page
- [ ] Tablet with excel smaller
- [ ] Link frontify user story.
- [ ] Replace "how wefox uses..." with "Read more about Ledgy for HR" linking to the HR sub-page
- [ ] The small gray "These CEOs and CFOs.." and "As featured in" seem like glued to the top of the grey rectangle
- [ ] "Read more about data protection" link doesn't work
- [ ] Replace "How Sherpany uses Ledgy for reporting" with "Learn more about investor features" linking to the investors sub-page
- [ ] CTAs "your cap table free forever" should be changed, but I guess this is in contentful, right?
- [ ] CTA spacing above looks too big compared to below

Pricing for startups
- [ ] Add the crowdfunding CTA at the bottom as in the mockup
- [ ] Adjust "less than 5m" to "less than 2m"
- [ ] standard €1 / signature --> €2 per signature
- [ ] border for free & premium thinner, enterprise thicker and bigger border radius, at least my taste :)
- [ ] the proportion of the houses doesn't emphasise enterprise enough. I adjusted the frame outline of the mockup images, so they're all the same, i.e. you can use them at the same width and the small house will appear much smaller.

Pricing for funds
- [ ] Looks too much spread out... I'd reduce the spacing between the lines a lot, and reduce the with of the boxes
- [ ] Also here my taste would be adjusted borders, see comment above

Webinar page: 
- [ ] Images pixelated and "cannot read property 0 of undefined" in console.

Calculator page: 
- [ ] missing padding between top part (dark background) and text

**Comment by morloy** [comment]
What the font…?

 - [ ] Fix font width in main heading
image

 - [ ] Fix font loading in Safari
image

**Comment by bbinoy** [comment]
- [ ] I noticed the Viu logo doesn't have transparent background
image
- [ ] buttons in footer have differing widths
image
- [ ] We'll rename the Premium package to Scaleup soon, but let's keep at Premium for now

**Comment by jahlela** [comment]
Oh, and your favorite topic :DDDD

The hover state for the white-gray buttons is a little dull. Maybe keeping the same background color, but still adding the shadow would be enough?

Screen Shot 2020-03-03 at 4 00 55 PM

**Pull request merged**
